#!/bin/bash

# To run this script: ./klee-run filename
# Filename can be test_exp, test_simple or test_sym

# Compile the source file into intermediate bitcode file
# You may consider bitcode is something equivalent to the level of bytecode

clang-9 -I $KLEE_DIR/include -emit-llvm -c -g -O0 -Xclang -disable-O0-optnone $1.c

# Run KLEE and produce SMT file for each path

klee --write-smt2s $1.bc
